config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :teas
  resources :frappuccinos
  resources :espressos
  resources :coffees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: redirect("/espressos")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coffee.rb
class Coffee < ApplicationRecord
end

app/models/espresso.rb
class Espresso < ApplicationRecord
  validates :name, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/frappuccino.rb
class Frappuccino < ApplicationRecord
end

app/models/tea.rb
class Tea < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :set_coffee, only: %i[ show edit update destroy ]

  # GET /coffees
  def index
    @search = Coffee.ransack(params[:q])
    @search.sorts = 'id desc' if @search.sorts.empty?
    @coffees = @search.result.page(params[:page])
  end

  # GET /coffees/1
  def show
  end

  # GET /coffees/new
  def new
    @coffee = Coffee.new
  end

  # GET /coffees/1/edit
  def edit
  end

  # POST /coffees
  def create
    @coffee = Coffee.new(coffee_params)

    if @coffee.save
      redirect_to @coffee, notice: "Coffee was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /coffees/1
  def update
    if @coffee.update(coffee_params)
      redirect_to @coffee, notice: "Coffee was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /coffees/1
  def destroy
    @coffee.destroy
    redirect_to coffees_url, notice: "Coffee was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee
      @coffee = Coffee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_params
      params.require(:coffee).permit(:name, :description)
    end
end

app/controllers/espressos_controller.rb
class EspressosController < ApplicationController
  before_action :set_espresso, only: %i[ show edit update destroy ]

  # GET /espressos
  def index
    @search = Espresso.ransack(params[:q])
    @search.sorts = 'id desc' if @search.sorts.empty?
    @espressos = @search.result.page(params[:page])
  end

  # GET /espressos/1
  def show
  end

  # GET /espressos/new
  def new
    @espresso = Espresso.new
  end

  # GET /espressos/1/edit
  def edit
  end

  # POST /espressos
  def create
    @espresso = Espresso.new(espresso_params)

    if @espresso.save
      redirect_to @espresso, notice: "Espresso was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /espressos/1
  def update
    if @espresso.update(espresso_params)
      flash.now.notice = "espressoを更新しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /espressos/1
  def destroy
    @espresso.destroy
    redirect_to espressos_url, notice: "Espresso was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_espresso
      @espresso = Espresso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def espresso_params
      params.require(:espresso).permit(:name, :description)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]

  # GET /foods
  def index
    @foods = Food.all
  end

  # GET /foods/1
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to @food, notice: "Food was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /foods/1
  def update
    if @food.update(food_params)
      redirect_to @food, notice: "Food was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /foods/1
  def destroy
    @food.destroy
    redirect_to foods_url, notice: "Food was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :description)
    end
end

app/controllers/frappuccinos_controller.rb
class FrappuccinosController < ApplicationController
  before_action :set_frappuccino, only: %i[ show edit update destroy ]

  # GET /frappuccinos
  def index
    @search = Frappuccino.ransack(params[:q])
    @search.sorts = 'id desc' if @search.sorts.empty?
    @frappuccinos = @search.result.page(params[:page])
  end

  # GET /frappuccinos/1
  def show
  end

  # GET /frappuccinos/new
  def new
    @frappuccino = Frappuccino.new
  end

  # GET /frappuccinos/1/edit
  def edit
  end

  # POST /frappuccinos
  def create
    @frappuccino = Frappuccino.new(frappuccino_params)

    if @frappuccino.save
      redirect_to @frappuccino, notice: "Frappuccino was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /frappuccinos/1
  def update
    if @frappuccino.update(frappuccino_params)
      redirect_to @frappuccino, notice: "Frappuccino was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /frappuccinos/1
  def destroy
    @frappuccino.destroy
    redirect_to frappuccinos_url, notice: "Frappuccino was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frappuccino
      @frappuccino = Frappuccino.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def frappuccino_params
      params.require(:frappuccino).permit(:name, :description)
    end
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController
  before_action :set_tea, only: %i[ show edit update destroy ]

  # GET /teas
  def index
    @search = Tea.ransack(params[:q])
    @search.sorts = 'id desc' if @search.sorts.empty?
    @coffees = @search.result.page(params[:page])
  end

  # GET /teas/1
  def show
  end

  # GET /teas/new
  def new
    @tea = Tea.new
  end

  # GET /teas/1/edit
  def edit
  end

  # POST /teas
  def create
    @tea = Tea.new(tea_params)

    if @tea.save
      redirect_to @tea, notice: "Tea was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /teas/1
  def update
    if @tea.update(tea_params)
      redirect_to @tea, notice: "Tea was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /teas/1
  def destroy
    @tea.destroy
    redirect_to teas_url, notice: "Tea was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tea
      @tea = Tea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tea_params
      params.require(:tea).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_to(path, emoji, text)
    classes = %w[my-1 nav-link text-white]
    classes << "active" if current_page?(path)

    link_to(path, class: classes) do
      tag.span(class: "me-2") { emoji } + tag.span { text }
    end
  end

  def icon(icon_name)
    tag.i(class: ["bi", "bi-#{icon_name}"])
  end

  def icon_with_text(icon_name, text)
    tag.span(icon(icon_name), class: "me-2") + tag.span(text)
  end

  def turbo_stream_flash
    turbo_stream.update "flash", partial: "flash"
  end
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/helpers/espressos_helper.rb
module EspressosHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/frappuccinos_helper.rb
module FrappuccinosHelper
end

app/helpers/teas_helper.rb
module TeasHelper
end

app/views/application/_flash.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <%= alert %>
  </div>
<% end %>

app/views/application/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 py-3 px-3 bg-dark text-white vh-100">
  <div class="d-flex align-items-center justify-content-center py-2">
    <%= link_to "MENU", root_path, class: "text-white display-6 text-decoration-none" %>
  </div>
  <hr />

  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= sidebar_link_to(espressos_path, "🐶", "Espressp") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(frappuccinos_path, "🐣", "Frappuccinos") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(teas_path, "🦔", "Tea") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(foods_path, "🦉", "Food") %>
    </li>
  </ul>
</div>

app/views/coffees/_coffee.html.erb
<div class="row py-2 border-top">
  <div class="col-4 my-auto">
    <%= coffee.name %>
  </div>
  <div class="col-4 my-auto">
    <%= coffee.description %>
  </div>
  <div class="col-4">
    <div class="d-flex justify-content-end">
      <%= link_to "編集", edit_coffee_path(coffee), class: "btn btn-sm btn-outline-primary me-2" %>
      <%= button_to "削除", coffee, method: :delete, class: "btn btn-sm btn-outline-danger" %>
    </div>
  </div>
</div>

app/views/coffees/_form.html.erb
<%= form_with(model: coffee) do |form| %>
  <% if coffee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coffee.errors.count, "error") %> prohibited this coffee from being saved:</h2>

      <ul>
        <% coffee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coffees/edit.html.erb
<h1>Coffeeを編集する</h1>

<%= render "form", coffee: @coffee %>

<br>

<div>
  <%= link_to "詳細", @coffee %> |
  <%= link_to "戻る", coffees_path %>
</div>

app/views/coffees/index.html.erb
<!-- 見出し -->
<h4 class="fw-bold">
  <span class="me-1">🐱</span>
  <span>Coffee</span>
</h4>

<!-- 検索フォーム -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("search", "検索条件") %>
  </div>

  <div class="card-body">
    <%= search_form_for @search do |f| %>
      <div class="row g3 mb-3">
        <div class="col-4 col-xl-2">
          <%= f.label :name_cont, "名前", class: "form-label" %>
          <%= f.search_field :name_cont, class: "form-control" %>
        </div>
        <div class="col-4 d-flex align-items-end">
          <%= button_tag(icon_with_text("search", "検索"), class: "btn btn-primary me-1") %>
          <%= link_to "リセット", coffees_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- 一覧 -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("table", "一覧") %>
  </div>

  <div class="card-body mx-3">
    <div class="row py-2">
      <div class="col-4 mt-auto">
        <%= sort_link(@search, :name) %>
      </div>
      <div class="col-4 mt-auto">
        <%= sort_link(@search, :description) %>
      </div>
      <div class="col-4 d-flex justify-content-end">
        <%= link_to icon_with_text("plus-circle", "登録"),
                    new_coffee_path,
                    class: "btn btn-outline-primary"
        %>
      </div>
    </div>

    <%= render @coffees %>

    <div class="d-flex justify-content-end mt-3">
      <%= paginate @coffees %>
    </div>
  </div>
</div>

app/views/coffees/new.html.erb
<h1>Coffeeを登録する</h1>

<%= render "form", cat: @coffee %>

<br>

<div>
  <%= link_to "戻る", coffees_path %>
</div>

app/views/coffees/show.html.erb
<div id="<%= dom_id @coffee %>">
  <p>
    <strong>名前:</strong>
    <%= @coffee.name %>
  </p>

  <p>
    <strong>説明:</strong>
    <%= @coffee.description %>
  </p>
</div>

<div>
  <%= link_to "編集", edit_coffee_path(@coffee) %> |
  <%= link_to "戻る", coffees_path %>
  <%= button_to "削除", @coffee, method: :delete %>
</div>

app/views/espressos/_espresso.html.erb
<%= turbo_frame_tag espresso do %>
  <div class="row py-2 border-top">
    <div class="col-4 my-auto">
      <%= espresso.name %>
    </div>
    <div class="col-4 my-auto">
      <%= espresso.description %>
    </div>
    <div class="col-4">
      <div class="d-flex justify-content-end">
        <%= link_to "編集", edit_espresso_path(espresso), class: "btn btn-sm btn-outline-primary me-2" %>
        <%= button_to "削除", espresso, method: :delete, class: "btn btn-sm btn-outline-danger" %>
      </div>
    </div>
  </div>
<% end %>

app/views/espressos/_form.html.erb
<%= turbo_frame_tag espresso do %>
  <%= bootstrap_form_with(model: espresso) do |form| %>

    <div class="row py-2 border-top">
      <div class="col-4">
        <%= form.text_field :name,
                            skip_label: true,
                            label_as_placeholder: true,
                            wrapper: false,
                            control_class: "form-control form-control-sm"
        %>
      </div>
      <div class="col-4">
        <%= form.text_field :description,
                            skip_label: true,
                            label_as_placeholder: true,
                            wrapper: false,
                            control_class: "form-control form-control-sm"
        %>
      </div>

      <div class="col-4">
        <div class="d-flex justify-content-end">
          <%= form.primary class: "btn btn-primary btn-sm me-2" %>
          <%= link_to "キャンセル", espresso, class: "btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
    </div>

  <% end %>
<% end %>

app/views/espressos/edit.html.erb
<h1>Editing espresso</h1>

<%= render "form", espresso: @espresso %>

<br>

<div>
  <%= link_to "Show this espresso", @espresso %> |
  <%= link_to "Back to espressos", espressos_path %>
</div>

app/views/espressos/index.html.erb
<!-- 見出し -->
<h4 class="fw-bold">
  <span class="me-1">🐱</span>
  <span>Espresso</span>
</h4>

<!-- 検索フォーム -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("search", "検索条件") %>
  </div>

  <div class="card-body">
    <%= search_form_for @search, html: { data: { turbo_frame: "espressos-list" } } do |f| %>
      <div class="row g3 mb-3">
        <div class="col-4 col-xl-2">
          <%= f.label :name_cont, "名前", class: "form-label" %>
          <%= f.search_field :name_cont, class: "form-control" %>
        </div>
        <div class="col-4 d-flex align-items-end">
          <%= button_tag(icon_with_text("search", "検索"), class: "btn btn-primary me-1") %>
          <%= link_to "リセット", espressos_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- 一覧 -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("table", "一覧") %>
  </div>

  <div class="card-body mx-3">
    <%= turbo_frame_tag "espressos-list" do %>
      <div class="row py-2">
        <div class="col-4 mt-auto">
          <%= sort_link(@search, :name) %>
        </div>
        <div class="col-4 mt-auto">
          <%= sort_link(@search, :description) %>
        </div>
        <div class="col-4 d-flex justify-content-end">
          <%= link_to icon_with_text("plus-circle", "登録"),
                      new_espresso_path,
                      class: "btn btn-outline-primary"
          %>
        </div>
      </div>

      <%= render @espressos %>

      <div class="d-flex justify-content-end mt-3">
        <%= paginate @espressos %>
      </div>
    <% end %>
  </div>
</div>

app/views/espressos/new.html.erb
<h1>New espresso</h1>

<%= render "form", espresso: @espresso %>

<br>

<div>
  <%= link_to "Back to espressos", espressos_path %>
</div>

app/views/espressos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @espresso %>

<div>
  <%= link_to "Edit this espresso", edit_espresso_path(@espresso) %> |
  <%= link_to "Back to espressos", espressos_path %>

  <%= button_to "Destroy this espresso", @espresso, method: :delete %>
</div>

app/views/espressos/update.turbo_stream.erb
<%= turbo_stream.replace @espresso %>
<%= turbo_stream_flash %>

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= food.description %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Foods</h1>

<div id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
    <p>
      <%= link_to "Show this food", food %>
    </p>
  <% end %>
</div>

<%= link_to "New food", new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/frappuccinos/_form.html.erb
<%# bootstrap_formを使ったフォームでは、form_withの代わりにbootstrap_form_withを使う %>
<%# バリデーションエラーの表示はbootstrap_formが用意してくれるので、自前で用意する必要がなくなる %>
<%= bootstrap_form_with(model: frappuccino) do |form| %>

 <%# ラベルはbootstrap_formが用意してくれるので、自前で用意する必要がなくなる %>
 <%# Bootstrapのclass属性もbootstrap_formが設定してくれるので、自前で用意する必要はない %>
 <%= form.text_field :name %>
 <%= form.number_field :description %>

 <%# Bootstrapのprimary色のsubmitボタン %>
 <%= form.primary %>
<% end %>

app/views/frappuccinos/_frappuccino.html.erb
<div class="row py-2 border-top">
  <div class="col-4 my-auto">
    <%= frappuccino.name %>
  </div>
  <div class="col-4 my-auto">
    <%= frappuccino.description %>
  </div>
  <div class="col-4">
    <div class="d-flex justify-content-end">
      <%= link_to "編集", edit_frappuccino_path( frappuccino), class: "btn btn-sm btn-outline-primary me-2" %>
      <%= button_to "削除",  frappuccino, method: :delete, class: "btn btn-sm btn-outline-danger" %>
    </div>
  </div>
</div>

app/views/frappuccinos/edit.html.erb
<h1>Editing frappuccino</h1>

<%= render "form", frappuccino: @frappuccino %>

<br>

<div>
  <%= link_to "Show this frappuccino", @frappuccino %> |
  <%= link_to "Back to frappuccinos", frappuccinos_path %>
</div>

app/views/frappuccinos/index.html.erb
<!-- 見出し -->
<h4 class="fw-bold">
  <span class="me-1">🐱</span>
  <span>frappuccino</span>
</h4>

<!-- 検索フォーム -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("search", "検索条件") %>
  </div>

  <div class="card-body">
    <%= search_form_for @search do |f| %>
      <div class="row g3 mb-3">
        <div class="col-4 col-xl-2">
          <%= f.label :name_cont, "名前", class: "form-label" %>
          <%= f.search_field :name_cont, class: "form-control" %>
        </div>
        <div class="col-4 d-flex align-items-end">
          <%= button_tag(icon_with_text("search", "検索"), class: "btn btn-primary me-1") %>
          <%= link_to "リセット",  frappuccinos_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- 一覧 -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("table", "一覧") %>
  </div>

  <div class="card-body mx-3">
    <div class="row py-2">
      <div class="col-4 mt-auto">
        <%= sort_link(@search, :name) %>
      </div>
      <div class="col-4 mt-auto">
        <%= sort_link(@search, :description) %>
      </div>
      <div class="col-4 d-flex justify-content-end">
        <%= link_to icon_with_text("plus-circle", "登録"),
                    new_frappuccino_path,
                    class: "btn btn-outline-primary"
        %>
      </div>
    </div>

    <%= render @frappuccinos %>

    <div class="d-flex justify-content-end mt-3">
      <%= paginate  @frappuccinos %>
    </div>
    
  </div>
</div>

app/views/frappuccinos/new.html.erb
<h1>New frappuccino</h1>

<%= render "form", frappuccino: @frappuccino %>

<br>

<div>
  <%= link_to "Back to frappuccinos", frappuccinos_path %>
</div>

app/views/frappuccinos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @frappuccino %>

<div>
  <%= link_to "Edit this frappuccino", edit_frappuccino_path(@frappuccino) %> |
  <%= link_to "Back to frappuccinos", frappuccinos_path %>

  <%= button_to "Destroy this frappuccino", @frappuccino, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
   <div class="vh-100">
      <div class="container-fluid">
        <div class="row">

          <div class="ps-0" style="width: 200px;"></div>
          <div class="ps-0 position-fixed" style="width: 200px;">
            <%= render "sidebar" %>
          </div>

          <div class="col my-4">
            <div id="flash">
              <%= render "flash" %>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/teas/_form.html.erb
<%# bootstrap_formを使ったフォームでは、form_withの代わりにbootstrap_form_withを使う %>
<%# バリデーションエラーの表示はbootstrap_formが用意してくれるので、自前で用意する必要がなくなる %>
<%= bootstrap_form_with(model: tea) do |form| %>

 <%# ラベルはbootstrap_formが用意してくれるので、自前で用意する必要がなくなる %>
 <%# Bootstrapのclass属性もbootstrap_formが設定してくれるので、自前で用意する必要はない %>
 <%= form.text_field :name %>
 <%= form.number_field :description %>

 <%# Bootstrapのprimary色のsubmitボタン %>
 <%= form.primary %>
<% end %>

app/views/teas/_tea.html.erb
<div id="<%= dom_id tea %>">
  <p>
    <strong>Name:</strong>
    <%= tea.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= tea.description %>
  </p>

</div>

app/views/teas/edit.html.erb
<h1>Editing tea</h1>

<%= render "form", tea: @tea %>

<br>

<div>
  <%= link_to "Show this tea", @tea %> |
  <%= link_to "Back to teas", teas_path %>
</div>

app/views/teas/index.html.erb
<!-- 見出し -->
<h4 class="fw-bold">
  <span class="me-1">🐱</span>
  <span>Tea</span>
</h4>

<!-- 検索フォーム -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("search", "検索条件") %>
  </div>

  <div class="card-body">
    <%= search_form_for @search do |f| %>
      <div class="row g3 mb-3">
        <div class="col-4 col-xl-2">
          <%= f.label :name_cont, "名前", class: "form-label" %>
          <%= f.search_field :name_cont, class: "form-control" %>
        </div>

        <div class="col-4 d-flex align-items-end">
          <%= button_tag(icon_with_text("search", "検索"), class: "btn btn-primary me-1") %>
          <%= link_to "リセット", teas_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- 一覧 -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("table", "一覧") %>
  </div>

  <div class="card-body mx-3">
    <div class="row py-2">
      <div class="col-4 mt-auto">
        <%= sort_link(@search, :name) %>
      </div>
      <div class="col-4 mt-auto">
        <%= sort_link(@search, :age) %>
      </div>
      <div class="col-4 d-flex justify-content-end">
        <%= link_to icon_with_text("plus-circle", "登録"),
                    new_tea_path,
                    class: "btn btn-outline-primary"
        %>
      </div>
    </div>


</div>

app/views/teas/new.html.erb
<h1>New tea</h1>

<%= render "form", tea: @tea %>

<br>

<div>
  <%= link_to "Back to teas", teas_path %>
</div>

app/views/teas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tea %>

<div>
  <%= link_to "Edit this tea", edit_tea_path(@tea) %> |
  <%= link_to "Back to teas", teas_path %>

  <%= button_to "Destroy this tea", @tea, method: :delete %>
</div>